# Generated by Django 6.0.4 on 2026-04-21 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('organization_id', models.BigIntegerField(unique=True)),
                ('organization_inn', models.CharField(blank=True, default='', max_length=64)),
                ('organization_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'external_organizations',
            },
        ),
        migrations.CreateModel(
            name='ExternalClassroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('class_room_id', models.BigIntegerField(unique=True)),
                ('class_room_name', models.CharField(max_length=255)),
                ('device_id', models.CharField(blank=True, default='', max_length=128)),
                ('auditorium', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_classrooms', to='cameras.auditorium')),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_classrooms', to='cameras.camera')),
                ('smart_camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_classrooms', to='cameras.smartcamera')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='integrations.externalorganization')),
            ],
            options={
                'db_table': 'external_classrooms',
            },
        ),
        migrations.CreateModel(
            name='ExternalClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('class_id', models.BigIntegerField(unique=True)),
                ('class_degree', models.IntegerField(blank=True, null=True)),
                ('class_name', models.CharField(max_length=100)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='integrations.externalorganization')),
            ],
            options={
                'db_table': 'external_classes',
            },
        ),
        migrations.CreateModel(
            name='ExternalStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('pinfl', models.CharField(max_length=32, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('class_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='integrations.externalclass')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='integrations.externalorganization')),
            ],
            options={
                'db_table': 'external_students',
            },
        ),
        migrations.CreateModel(
            name='ExternalSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('lesson_number', models.IntegerField()),
                ('date', models.DateField()),
                ('timezone', models.CharField(default='Asia/Tashkent', max_length=64)),
                ('start_at', models.TimeField()),
                ('end_at', models.TimeField()),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='integrations.externalclass')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='integrations.externalclassroom')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='integrations.externalorganization')),
            ],
            options={
                'db_table': 'external_schedules',
                'constraints': [models.UniqueConstraint(fields=('organization', 'class_obj', 'classroom', 'lesson_number', 'date'), name='external_schedule_unique_lesson')],
            },
        ),
        migrations.CreateModel(
            name='ExternalStudentPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('photo_type', models.CharField(choices=[('front', 'Front'), ('up', 'Up'), ('left', 'Left'), ('right', 'Right'), ('bottom', 'Bottom')], max_length=20)),
                ('photo_guid', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='external_students/photos/')),
                ('image_base64', models.TextField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='integrations.externalstudent')),
            ],
            options={
                'db_table': 'external_student_photos',
                'constraints': [models.UniqueConstraint(fields=('student', 'photo_type'), name='external_student_photo_type_uniq')],
            },
        ),
    ]
