# Generated by Django 6.0.4 on 2026-05-16 07:26

import apps.common.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_add_indexes_and_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalstudentphoto',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=apps.common.storage.MinioStudentPhotoStorage(), upload_to='external_students/photos/'),
        ),
    ]
