# Generated by Django 6.0.4 on 2026-04-21 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.TextField()),
                ('ip_address', models.TextField()),
                ('username', models.TextField()),
                ('password', models.TextField()),
                ('rtsp_url_format', models.CharField(blank=True, max_length=16, null=True)),
                ('camera_number', models.TextField(blank=True, null=True)),
                ('stream_quality', models.IntegerField(blank=True, null=True)),
                ('owner_id', models.IntegerField(blank=True, null=True)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('path', models.TextField(blank=True, null=True)),
                ('channel', models.IntegerField(blank=True, null=True)),
                ('is_main_stream', models.BooleanField(blank=True, null=True)),
                ('skud_device_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
            ],
            options={
                'db_table': 'cameras',
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('hemis_id', models.BigIntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('camera_count', models.IntegerField(blank=True, null=True)),
                ('active_camera_count', models.IntegerField(blank=True, null=True)),
                ('person_count', models.IntegerField(blank=True, null=True)),
                ('active_person_count', models.IntegerField(blank=True, null=True)),
                ('max_floor_count', models.IntegerField(blank=True, null=True)),
                ('min_floor_count', models.IntegerField(blank=True, null=True)),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buildings', to='academics.university')),
            ],
            options={
                'db_table': 'building',
            },
        ),
        migrations.CreateModel(
            name='Auditorium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('hemis_id', models.BigIntegerField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('camera_count', models.IntegerField(blank=True, null=True)),
                ('active_camera_count', models.IntegerField(blank=True, null=True)),
                ('person_count', models.IntegerField(blank=True, null=True)),
                ('active_person_count', models.IntegerField(blank=True, null=True)),
                ('hemis_status', models.CharField(max_length=16)),
                ('auditorium_type', models.ForeignKey(blank=True, db_column='auditoriumType_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorium_types', to='academics.reference')),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditoriums', to='cameras.building')),
            ],
            options={
                'db_table': 'auditorium',
            },
        ),
        migrations.CreateModel(
            name='CameraROI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('roi_x', models.IntegerField()),
                ('roi_y', models.IntegerField()),
                ('roi_width', models.IntegerField()),
                ('roi_height', models.IntegerField()),
                ('frame_width', models.IntegerField(blank=True, null=True)),
                ('frame_height', models.IntegerField(blank=True, null=True)),
                ('camera', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roi', to='cameras.camera')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_rois', to='common.user')),
            ],
            options={
                'db_table': 'camera_rois',
            },
        ),
        migrations.CreateModel(
            name='SmartCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.TextField()),
                ('device_id', models.TextField(unique=True)),
                ('device_mac', models.TextField(unique=True)),
                ('lib_platform_version', models.TextField(blank=True, null=True)),
                ('software_version', models.TextField(blank=True, null=True)),
                ('lib_ai_version', models.TextField(blank=True, null=True)),
                ('device_ip', models.TextField(blank=True, null=True)),
                ('time_stamp', models.TextField(blank=True, null=True)),
                ('rtsp_url_format', models.CharField(blank=True, max_length=16, null=True)),
                ('hearbeat', models.TextField(blank=True, null=True)),
                ('login', models.TextField()),
                ('password', models.TextField()),
                ('device_name', models.TextField(blank=True, null=True)),
                ('device_lan', models.TextField(blank=True, null=True)),
                ('device_lon', models.TextField(blank=True, null=True)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('path', models.TextField(blank=True, null=True)),
                ('channel', models.IntegerField(blank=True, null=True)),
                ('is_main_stream', models.BooleanField(blank=True, null=True)),
                ('auditorium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smart_cameras', to='cameras.auditorium')),
            ],
            options={
                'db_table': 'smart_cameras',
            },
        ),
        migrations.CreateModel(
            name='AuditoriumCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auditorium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorium_cameras', to='cameras.auditorium')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camera_auditoriums', to='cameras.camera')),
            ],
            options={
                'db_table': 'auditorium_camera',
                'constraints': [models.UniqueConstraint(fields=('auditorium', 'camera'), name='auditorium_camera_uniq')],
            },
        ),
    ]
