# Generated by Django 6.0.4 on 2026-04-29 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='is_active_stream',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='camera',
            name='organization_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='stream_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
