# Generated by Django 6.0.4 on 2026-05-18 05:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0005_camera_ptz_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='patrol_dwell_seconds',
            field=models.FloatField(default=3.0, help_text='Har nuqtada necha soniya turadi (AI shu paytda taniydi)'),
        ),
        migrations.AddField(
            model_name='camera',
            name='patrol_mode',
            field=models.CharField(choices=[('default', 'Global sozlama'), ('off', "O'chiq (statik)"), ('preset', "Preset bo'ylab"), ('sweep', 'Avtomatik sweep'), ('hybrid', 'Gibrid')], default='default', max_length=16),
        ),
        migrations.AddField(
            model_name='camera',
            name='patrol_pan_max',
            field=models.FloatField(default=0.6, help_text="ONVIF normalized pan [-1..1] o'ng chegara"),
        ),
        migrations.AddField(
            model_name='camera',
            name='patrol_pan_min',
            field=models.FloatField(default=-0.6, help_text='ONVIF normalized pan [-1..1] chap chegara'),
        ),
        migrations.AddField(
            model_name='camera',
            name='patrol_steps',
            field=models.IntegerField(default=3, help_text="Sweep nechta nuqtaga bo'linadi"),
        ),
        migrations.AddField(
            model_name='camera',
            name='patrol_tilt',
            field=models.FloatField(default=0.0, help_text='ONVIF normalized tilt [-1..1]'),
        ),
        migrations.AddField(
            model_name='camera',
            name='patrol_zoom',
            field=models.FloatField(default=0.0, help_text='ONVIF normalized zoom [0..1]'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='ptz_preset_token',
            field=models.CharField(blank=True, help_text="ONVIF home preset token (dars yo'q paytda shu pozitsiya)", max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='CameraPatrolPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.IntegerField(default=0, help_text='Aylanish tartibi (0,1,2...)')),
                ('preset_token', models.CharField(help_text='ONVIF preset token', max_length=64)),
                ('label', models.CharField(blank=True, help_text="Masalan: chap_qator, markaz, o'ng_qator", max_length=64, null=True)),
                ('dwell_seconds', models.FloatField(blank=True, help_text="Bo'sh bo'lsa Camera.patrol_dwell_seconds ishlatiladi", null=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patrol_points', to='cameras.camera')),
            ],
            options={
                'db_table': 'camera_patrol_points',
                'ordering': ['camera_id', 'order'],
                'constraints': [models.UniqueConstraint(fields=('camera', 'order'), name='camera_patrol_order_uniq')],
            },
        ),
    ]
