# Generated by Django 6.0.4 on 2026-04-21 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('hemis_id', models.BigIntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('classifier', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'classifier',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('hemis_id', models.BigIntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('parent', models.BigIntegerField(blank=True, null=True)),
                ('active', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('hemis_id', models.BigIntegerField(blank=True, null=True)),
                ('lesson_pair', models.JSONField(blank=True, db_column='lessonPair', null=True)),
                ('lesson_date', models.BigIntegerField(blank=True, null=True)),
                ('hemis_status', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'schedule',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('hemis_id', models.BigIntegerField(blank=True, null=True)),
                ('curriculum_id', models.BigIntegerField(blank=True, null=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('avg_gpa', models.FloatField(blank=True, null=True)),
                ('avg_grade', models.FloatField(blank=True, null=True)),
                ('birth_date', models.BigIntegerField(blank=True, null=True)),
                ('student_id_number', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('second_name', models.CharField(blank=True, max_length=255, null=True)),
                ('third_name', models.CharField(blank=True, max_length=255, null=True)),
                ('short_name', models.CharField(blank=True, max_length=255, null=True)),
                ('hash', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('is_graduate', models.BooleanField(blank=True, null=True)),
                ('other', models.CharField(blank=True, max_length=255, null=True)),
                ('roommate_count', models.BigIntegerField(blank=True, null=True)),
                ('total_acload', models.BigIntegerField(blank=True, null=True)),
                ('total_credit', models.BigIntegerField(blank=True, null=True)),
                ('validate_url', models.CharField(blank=True, max_length=255, null=True)),
                ('year_of_enter', models.BigIntegerField(blank=True, null=True)),
                ('hemis_status', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('hemis_id', models.BigIntegerField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subject',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('api_url', models.CharField(blank=True, max_length=255, null=True)),
                ('logo', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'university',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('hemis_id', models.BigIntegerField(blank=True, null=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('second_name', models.CharField(blank=True, max_length=255, null=True)),
                ('third_name', models.CharField(blank=True, max_length=255, null=True)),
                ('short_name', models.CharField(blank=True, max_length=255, null=True)),
                ('birth_date', models.BigIntegerField(blank=True, null=True)),
                ('contract_date', models.BigIntegerField(blank=True, null=True)),
                ('contract_number', models.CharField(blank=True, max_length=255, null=True)),
                ('decree_date', models.BigIntegerField(blank=True, null=True)),
                ('decree_number', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_id_number', models.CharField(blank=True, max_length=255, null=True)),
                ('hash', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_id', models.BigIntegerField(blank=True, null=True)),
                ('speciality', models.CharField(blank=True, max_length=255, null=True)),
                ('year_of_enter', models.BigIntegerField(blank=True, null=True)),
                ('hemis_status', models.CharField(max_length=16)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='academics.department')),
                ('faculty', models.ForeignKey(blank=True, db_column='faculty_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty_employees', to='academics.department')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('hemis_id', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('parent', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(blank=True, null=True)),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('classifier', models.ForeignKey(blank=True, db_column='classifier_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='references', to='academics.classifier')),
            ],
            options={
                'db_table': 'reference',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('hemis_id', models.BigIntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('hemis_status', models.CharField(max_length=16)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='academics.department')),
                ('tutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutor_groups', to='academics.employee')),
                ('specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_specialties', to='academics.reference')),
            ],
            options={
                'db_table': 'group',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='academic_degree',
            field=models.ForeignKey(blank=True, db_column='academicDegree_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_academic_degrees', to='academics.reference'),
        ),
        migrations.AddField(
            model_name='employee',
            name='academic_rank',
            field=models.ForeignKey(blank=True, db_column='academicRank_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_academic_ranks', to='academics.reference'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_status',
            field=models.ForeignKey(blank=True, db_column='employeeStatus_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_statuses', to='academics.reference'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_type',
            field=models.ForeignKey(blank=True, db_column='employeeType_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_types', to='academics.reference'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employment_form',
            field=models.ForeignKey(blank=True, db_column='employmentForm_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_employment_forms', to='academics.reference'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employment_staff',
            field=models.ForeignKey(blank=True, db_column='employmentStaff_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_employment_staffs', to='academics.reference'),
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_genders', to='academics.reference'),
        ),
        migrations.AddField(
            model_name='employee',
            name='staff_position',
            field=models.ForeignKey(blank=True, db_column='staffPosition_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_staff_positions', to='academics.reference'),
        ),
        migrations.AddField(
            model_name='department',
            name='locality_type',
            field=models.ForeignKey(blank=True, db_column='localityType_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_locality_types', to='academics.reference'),
        ),
        migrations.AddField(
            model_name='department',
            name='structure_type',
            field=models.ForeignKey(blank=True, db_column='structureType_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_structure_types', to='academics.reference'),
        ),
    ]
