# Generated by Django 6.0.4 on 2026-04-21 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='auditorium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='cameras.auditorium'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='academics.department'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='academics.employee'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='faculty',
            field=models.ForeignKey(blank=True, db_column='faculty_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty_schedules', to='academics.department'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='academics.group'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_semesters', to='academics.reference'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='training_type',
            field=models.ForeignKey(blank=True, db_column='trainingType_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_training_types', to='academics.reference'),
        ),
        migrations.AddField(
            model_name='student',
            name='accommodation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_accommodations', to='academics.reference'),
        ),
        migrations.AddField(
            model_name='student',
            name='citizenship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_citizenships', to='academics.reference'),
        ),
        migrations.AddField(
            model_name='student',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_countries', to='academics.reference'),
        ),
        migrations.AddField(
            model_name='student',
            name='current_district',
            field=models.ForeignKey(blank=True, db_column='currentDistrict_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_current_districts', to='academics.reference'),
        ),
        migrations.AddField(
            model_name='student',
            name='current_province',
            field=models.ForeignKey(blank=True, db_column='currentProvince_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_current_provinces', to='academics.reference'),
        ),
        migrations.AddField(
            model_name='student',
            name='current_terrain',
            field=models.ForeignKey(blank=True, db_column='currentTerrain_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_current_terrains', to='academics.reference'),
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.department'),
        ),
        migrations.AddField(
            model_name='student',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_districts', to='academics.reference'),
        ),
        migrations.AddField(
            model_name='student',
            name='education_form',
            field=models.ForeignKey(blank=True, db_column='educationForm_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_education_forms', to='academics.reference'),
        ),
        migrations.AddField(
            model_name='student',
            name='education_type',
            field=models.ForeignKey(blank=True, db_column='educationType_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_education_types', to='academics.reference'),
        ),
        migrations.AddField(
            model_name='student',
            name='education_year',
            field=models.ForeignKey(blank=True, db_column='educationYear_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_education_years', to='academics.reference'),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_genders', to='academics.reference'),
        ),
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.group'),
        ),
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_levels', to='academics.reference'),
        ),
        migrations.AddField(
            model_name='student',
            name='payment_form',
            field=models.ForeignKey(blank=True, db_column='paymentForm_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_payment_forms', to='academics.reference'),
        ),
        migrations.AddField(
            model_name='student',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_provinces', to='academics.reference'),
        ),
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_semesters', to='academics.reference'),
        ),
        migrations.AddField(
            model_name='student',
            name='social_category',
            field=models.ForeignKey(blank=True, db_column='socialCategory_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_social_categories', to='academics.reference'),
        ),
        migrations.AddField(
            model_name='student',
            name='specialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_specialties', to='academics.reference'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_status',
            field=models.ForeignKey(blank=True, db_column='studentStatus_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_statuses', to='academics.reference'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_type',
            field=models.ForeignKey(blank=True, db_column='studentType_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_types', to='academics.reference'),
        ),
        migrations.AddField(
            model_name='student',
            name='terrain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_terrains', to='academics.reference'),
        ),
        migrations.AddField(
            model_name='student',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_universities', to='academics.reference'),
        ),
        migrations.AddField(
            model_name='subject',
            name='education_type',
            field=models.ForeignKey(blank=True, db_column='educationType_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_education_types', to='academics.reference'),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_group',
            field=models.ForeignKey(blank=True, db_column='subjectGroup_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_groups', to='academics.reference'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='academics.subject'),
        ),
    ]
