# Generated by Django 6.0.4 on 2026-04-23 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_data', '0001_initial'),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('valid', 'Valid'), ('no_face', 'No face'), ('multi_face', 'Multiple faces'), ('blurry', 'Blurry'), ('too_small', 'Too small'), ('failed', 'Failed'), ('embedded', 'Embedded')], default='pending', max_length=20)),
                ('face_count', models.IntegerField(default=0)),
                ('blur_score', models.FloatField(blank=True, null=True)),
                ('face_width', models.IntegerField(blank=True, null=True)),
                ('face_height', models.IntegerField(blank=True, null=True)),
                ('quality_score', models.FloatField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('aligned_image', models.ImageField(blank=True, null=True, upload_to='enrollment/aligned/')),
                ('external_photo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_record', to='integrations.externalstudentphoto')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_photos', to='integrations.externalstudent')),
            ],
            options={
                'db_table': 'enrollment_photos',
            },
        ),
        migrations.CreateModel(
            name='StudentEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('model_name', models.CharField(choices=[('arcface', 'ArcFace'), ('custom', 'Custom')], default='arcface', max_length=32)),
                ('model_version', models.CharField(blank=True, default='', max_length=64)),
                ('embedding', models.JSONField()),
                ('embedding_dim', models.IntegerField(default=512)),
                ('is_primary', models.BooleanField(default=False)),
                ('quality_score', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('enrollment_photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='face_data.enrollmentphoto')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_embeddings', to='integrations.externalstudent')),
            ],
            options={
                'db_table': 'student_embeddings',
            },
        ),
    ]
