# Generated by Django 6.0.4 on 2026-05-04 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_data', '0003_studentembedding_pgvector'),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='studentembedding',
            index=models.Index(fields=['is_active'], name='se_is_active_idx'),
        ),
        migrations.AddIndex(
            model_name='studentembedding',
            index=models.Index(fields=['student_id', 'is_active'], name='se_student_active_idx'),
        ),
    ]
