# Generated by Django 6.0.4 on 2026-05-04 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face_data', '0004_add_db_indexes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FaceData',
        ),
    ]
