# Generated by Django 6.0.6 on 2026-07-20 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_data', '0006_studentembedding_hnsw_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentembedding',
            name='source',
            field=models.CharField(choices=[('enrollment', 'Enrollment'), ('camera', 'Camera')], default='enrollment', max_length=16),
        ),
        migrations.AddField(
            model_name='studentembedding',
            name='source_meta',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentembedding',
            name='enrollment_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='face_data.enrollmentphoto'),
        ),
    ]
