# Generated by Django 6.0.6 on 2026-07-20 11:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrations', '0003_minio_student_photo_storage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotSentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('report_type', models.CharField(choices=[('lesson', 'Dars hisoboti'), ('daily', 'Kunlik hisobot')], max_length=16)),
                ('report_date', models.DateField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bot_reports', to='integrations.externalschedule')),
            ],
            options={
                'db_table': 'bot_sent_reports',
                'indexes': [models.Index(fields=['report_type', 'report_date'], name='bsr_type_date_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('schedule__isnull', False)), fields=('report_type', 'schedule'), name='bsr_unique_lesson_report'), models.UniqueConstraint(condition=models.Q(('schedule__isnull', True)), fields=('report_type', 'report_date'), name='bsr_unique_daily_report')],
            },
        ),
    ]
