# Generated by Django 6.0.4 on 2026-04-21 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('arrived_time', models.BigIntegerField(blank=True, null=True)),
                ('lesson_time', models.BigIntegerField(blank=True, null=True)),
                ('lesson_date', models.BigIntegerField(blank=True, null=True)),
                ('is_late', models.BooleanField(blank=True, null=True)),
                ('requested', models.BooleanField(blank=True, null=True)),
                ('image_base64', models.TextField(blank=True, null=True)),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_attendances', to='academics.schedule')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_attendances', to='academics.student')),
            ],
            options={
                'db_table': 'ai_attendance',
            },
        ),
        migrations.CreateModel(
            name='AiAttendanceEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('arrived_time', models.BigIntegerField(blank=True, null=True)),
                ('lesson_time', models.BigIntegerField(blank=True, null=True)),
                ('lesson_date', models.BigIntegerField(blank=True, null=True)),
                ('is_late', models.BooleanField(blank=True, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_attendance_employees', to='academics.employee')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_attendance_employees', to='academics.schedule')),
            ],
            options={
                'db_table': 'ai_attendance_employee',
            },
        ),
        migrations.CreateModel(
            name='AiAttendanceFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=256, null=True)),
                ('camera_id', models.BigIntegerField(blank=True, null=True)),
                ('timestamp', models.BigIntegerField(blank=True, null=True)),
                ('similarity', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=16, null=True)),
                ('source', models.CharField(blank=True, max_length=16, null=True)),
                ('needs_review', models.BooleanField(blank=True, null=True)),
                ('confirmed_by', models.BigIntegerField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('image_base64', models.TextField(blank=True, null=True)),
                ('lesson_date', models.BigIntegerField(blank=True, null=True)),
                ('ai_attendance', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_record', to='attendance.aiattendance')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_attendance_finals', to='academics.schedule')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_attendance_finals', to='academics.student')),
            ],
            options={
                'db_table': 'ai_attendance_final',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('hemis_id', models.BigIntegerField(blank=True, null=True)),
                ('absent_off', models.IntegerField(blank=True, null=True)),
                ('absent_on', models.IntegerField(blank=True, null=True)),
                ('lesson_date', models.IntegerField(blank=True, null=True)),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='academics.schedule')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='academics.student')),
            ],
            options={
                'db_table': 'attendance',
            },
        ),
    ]
