# Generated by Django 6.0.4 on 2026-04-24 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('cameras', '0001_initial'),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('organization_id', models.BigIntegerField(blank=True, null=True)),
                ('locked_from', models.DateTimeField()),
                ('locked_until', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('reason', models.CharField(default='attendance_done', max_length=64)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_locks', to='cameras.camera')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_locks', to='integrations.externalstudent')),
            ],
            options={
                'db_table': 'attendance_locks',
            },
        ),
    ]
