# Generated by Django 6.0.4 on 2026-04-24 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancelock'),
        ('cameras', '0001_initial'),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecognitionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('organization_id', models.BigIntegerField(blank=True, null=True)),
                ('full_name', models.CharField(blank=True, default='', max_length=255)),
                ('pinfl', models.CharField(blank=True, default='', max_length=32)),
                ('recognized_at', models.DateTimeField()),
                ('similarity', models.FloatField(blank=True, null=True)),
                ('decision', models.CharField(choices=[('accepted', 'Accepted'), ('review', 'Review'), ('rejected', 'Rejected')], max_length=16)),
                ('source', models.CharField(default='ai', max_length=32)),
                ('model_name', models.CharField(default='buffalo_l', max_length=64)),
                ('image', models.ImageField(blank=True, null=True, upload_to='recognition_events/')),
                ('image_base64', models.TextField(blank=True, null=True)),
                ('meta_json', models.JSONField(blank=True, null=True)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recognition_events', to='cameras.camera')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recognition_events', to='integrations.externalstudent')),
            ],
            options={
                'db_table': 'recognition_events',
            },
        ),
    ]
