# Generated by Django 6.0.4 on 2026-04-24 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_recognitionevent'),
        ('cameras', '0001_initial'),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('track_key', models.CharField(max_length=128, unique=True)),
                ('organization_id', models.BigIntegerField(blank=True, null=True)),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('recognized_at', models.DateTimeField(blank=True, null=True)),
                ('best_score', models.FloatField(blank=True, null=True)),
                ('last_score', models.FloatField(blank=True, null=True)),
                ('frame_count', models.IntegerField(default=0)),
                ('recognition_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('new', 'New'), ('tracking', 'Tracking'), ('recognized', 'Recognized'), ('skipped_locked', 'Skipped locked'), ('lost', 'Lost')], default='new', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('bbox_x1', models.IntegerField(blank=True, null=True)),
                ('bbox_y1', models.IntegerField(blank=True, null=True)),
                ('bbox_x2', models.IntegerField(blank=True, null=True)),
                ('bbox_y2', models.IntegerField(blank=True, null=True)),
                ('meta_json', models.JSONField(blank=True, null=True)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='track_sessions', to='cameras.camera')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='track_sessions', to='integrations.externalstudent')),
            ],
            options={
                'db_table': 'track_sessions',
            },
        ),
    ]
