# Generated by Django 6.0.4 on 2026-05-04 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_tracksession'),
        ('cameras', '0002_add_stream_url_to_camera'),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendancelock',
            index=models.Index(fields=['student_id', 'is_active', 'locked_until'], name='al_student_lock_idx'),
        ),
        migrations.AddIndex(
            model_name='recognitionevent',
            index=models.Index(fields=['decision', 'recognized_at'], name='re_decision_date_idx'),
        ),
        migrations.AddIndex(
            model_name='recognitionevent',
            index=models.Index(fields=['organization_id', 'recognized_at'], name='re_org_date_idx'),
        ),
    ]
