# Generated by Django 6.0.4 on 2026-05-15 15:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_tracksession_frontal_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiattendancefinal',
            name='ai_attendance',
        ),
        migrations.RemoveField(
            model_name='aiattendanceemployee',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='aiattendanceemployee',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='aiattendancefinal',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='aiattendancefinal',
            name='student',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='student',
        ),
        migrations.AlterField(
            model_name='attendancelock',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='attendancelock',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='lessonattendance',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='lessonattendance',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='recognitionevent',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='recognitionevent',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tracksession',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tracksession',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='AiAttendance',
        ),
        migrations.DeleteModel(
            name='AiAttendanceEmployee',
        ),
        migrations.DeleteModel(
            name='AiAttendanceFinal',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
