# Generated by Django 6.0.4 on 2026-05-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_remove_legacy_models'),
        ('cameras', '0003_add_indexes_and_constraints'),
        ('integrations', '0002_add_indexes_and_constraints'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tracksession',
            index=models.Index(fields=['is_active', 'last_seen_at'], name='ts_active_last_seen_idx'),
        ),
        migrations.AddIndex(
            model_name='tracksession',
            index=models.Index(fields=['student_id', 'is_active'], name='ts_student_active_idx'),
        ),
        migrations.AddIndex(
            model_name='tracksession',
            index=models.Index(fields=['camera_id', 'is_active'], name='ts_camera_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendancelock',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('student_id', 'camera_id'), name='al_unique_active_lock'),
        ),
    ]
