# Generated by Django 6.0.4 on 2026-05-16 07:26

import apps.common.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_add_indexes_and_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recognitionevent',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=apps.common.storage.MinioRecognitionStorage(), upload_to='recognition_events/'),
        ),
    ]
