# Generated by Django 6.0.4 on 2026-05-16 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_minio_recognition_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='recognitionevent',
            name='skud_push_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recognitionevent',
            name='skud_pushed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
