# Generated by Django 6.0.4 on 2026-05-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_skud_push_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='recognitionevent',
            name='skud_push_attempts',
            field=models.SmallIntegerField(default=0),
        ),
    ]
